import { ItemCategory, LostItemReport } from './types';

export const ITEM_CATEGORIES: { name: ItemCategory; iconName: string; placeholder: string }[] = [
  {
    name: 'Electronics & Gadgets',
    iconName: 'Smartphone',
    placeholder: 'e.g. MacBook Pro 14", iPhone 15 Pro, Sony WH-1000XM5 headphones',
  },
  {
    name: 'Wallets & Money',
    iconName: 'Wallet',
    placeholder: 'e.g. Brown leather bifold, cardholder with ID slot',
  },
  {
    name: 'Bags & Luggage',
    iconName: 'Briefcase',
    placeholder: 'e.g. Black North Face Borealis backpack, canvas tote bag',
  },
  {
    name: 'Keys & Fobs',
    iconName: 'Key',
    placeholder: 'e.g. Subaru car key fob with blue carabiner & Swiss army knife',
  },
  {
    name: 'IDs & Documentation',
    iconName: 'CreditCard',
    placeholder: 'e.g. State Driver License, Student ID, International Passport',
  },
  {
    name: 'Clothing & Outerwear',
    iconName: 'Shirt',
    placeholder: 'e.g. Patagonia fleece jacket, navy wool scarf, baseball cap',
  },
  {
    name: 'Eyewear & Glasses',
    iconName: 'Glasses',
    placeholder: 'e.g. Ray-Ban tortoiseshell sunglasses, wire-rim prescription frames',
  },
  {
    name: 'Jewelry & Watches',
    iconName: 'Watch',
    placeholder: 'e.g. Silver Seiko automatic watch, gold signet ring',
  },
  {
    name: 'Books & Notebooks',
    iconName: 'Book',
    placeholder: 'e.g. Black Moleskine sketchbook, Organic Chemistry textbook',
  },
  {
    name: 'Other Belongings',
    iconName: 'Package',
    placeholder: 'e.g. Hydro Flask 32oz water bottle, folding umbrella',
  },
];

export const POPULAR_LOCATIONS = [
  'Central Library - 2nd Floor Study Tables',
  'Main Dining Commons - South Seating Area',
  'Student Recreation Center - Locker Room B',
  'Science Building - Lecture Hall 101',
  'Campus Transit Terminal - Bus Bay 4',
  'Engineering Quad - West Courtyard Benches',
  'Administration Hall - 1st Floor Reception',
  'Art & Architecture Annex - Workshop 3',
];

export const COLOR_OPTIONS = [
  { name: 'Black', hex: '#18181b' },
  { name: 'Gray / Silver', hex: '#71717a' },
  { name: 'White', hex: '#f4f4f5' },
  { name: 'Blue / Navy', hex: '#1d4ed8' },
  { name: 'Brown / Tan', hex: '#78350f' },
  { name: 'Red / Maroon', hex: '#b91c1c' },
  { name: 'Green', hex: '#15803d' },
  { name: 'Gold / Yellow', hex: '#ca8a04' },
  { name: 'Purple', hex: '#7e22ce' },
  { name: 'Multi-color', hex: '#9333ea' },
];

export const SAMPLE_REPORTS: LostItemReport[] = [
  {
    id: 'LTR-2026-84920',
    firstName: 'Marcus',
    lastName: 'Vance',
    email: 'marcus.vance@example.com',
    phone: '+1 (555) 234-8901',
    itemType: 'Electronics & Gadgets',
    itemTitle: 'Apple iPad Air (5th Gen) Space Gray',
    color: 'Gray / Silver',
    location: 'Central Library - 2nd Floor Study Tables',
    locationDetails: 'Desk 14 near the east window row, had dark navy magnetic folio case.',
    lostDate: '2026-10-06',
    lostTime: '15:30',
    description: 'Space Gray 64GB iPad Air with an Apple Pencil attached to the top magnetic charging strip. Lock screen has a mountain landscape photograph.',
    identifyingFeatures: 'Small scratch on top-left aluminum bezel, blue matte skin on the back.',
    isUrgent: true,
    hasReward: false,
    status: 'potential_match',
    createdAt: '2026-10-06T16:15:00.000Z',
    deskNotes: 'An iPad Air matching this description was logged at the 2nd Floor Circulation Desk today at 17:00. Please contact desk to verify passcode.',
  },
  {
    id: 'LTR-2026-72411',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.rostova@example.com',
    phone: '+1 (555) 789-1122',
    itemType: 'Wallets & Money',
    itemTitle: 'Celine Card Holder in Burgundy Pebble Leather',
    color: 'Red / Maroon',
    location: 'Main Dining Commons - South Seating Area',
    locationDetails: 'Booth table 8, near the juice bar checkout station.',
    lostDate: '2026-10-07',
    lostTime: '12:45',
    description: 'Burgundy grained calfskin cardholder containing transit pass, university student ID card with name Elena Rostova, and debit card.',
    identifyingFeatures: 'Embossed gold lettering "CELINE PARIS" slightly faded on the bottom edge.',
    isUrgent: true,
    hasReward: true,
    rewardAmount: '$50',
    status: 'ready_for_pickup',
    createdAt: '2026-10-07T13:20:00.000Z',
    deskNotes: 'Turned in by custodial staff at 14:10. Held securely in Vault Safe #2 at the Central Lost & Found Office.',
  },
  {
    id: 'LTR-2026-61904',
    firstName: 'David',
    lastName: 'Chen',
    email: 'd.chen@example.com',
    phone: '+1 (555) 341-9988',
    itemType: 'Keys & Fobs',
    itemTitle: 'Toyota Key Fob + Gym Tag + Brass Key',
    color: 'Black',
    location: 'Student Recreation Center - Locker Room B',
    locationDetails: 'Bench in locker aisle 4 near shower exit.',
    lostDate: '2026-10-07',
    lostTime: '08:15',
    description: 'Key ring with 1 black Toyota push-start fob, 1 brass house key, 1 small silver bike lock key, and a green gym barcode scan tag.',
    identifyingFeatures: 'Green climbing carabiner clip and miniature red paracord knot.',
    isUrgent: false,
    hasReward: false,
    status: 'under_review',
    createdAt: '2026-10-07T09:00:00.000Z',
    deskNotes: 'Staff sweep of locker room scheduled for 18:00 shift change.',
  },
];
